version: '3.8'
services:
  api:
    build:
      context: .
      target: development
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:p4ssw0rd@db:5432/db
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
      - '9229:9229'
    command: npm run start:debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p4ssw0rd
      - POSTGRES_DB=db
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
